<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Courseteacher extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Courseteacher_model');
         $this->load->model('Course_model');
          $this->load->model('Teacher_model');
    } 

    /*
     * Listing of tblcourseteacher
     */
    function index()
    {
        $data['tblcourseteacher'] = $this->Courseteacher_model->get_all_tblcourseteacher_tblteacher_tblcourse();
        
        $data['_view'] = 'courseteacher/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tblcourseteacher
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('course_id','Course Id','required');
		$this->form_validation->set_rules('teacher_id','Teacher Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'course_id' => $this->input->post('course_id'),
				'teacher_id' => $this->input->post('teacher_id'),
            );
            
            $tblcourseteacher_id = $this->Courseteacher_model->add_tblcourseteacher($params);
            redirect('courseteacher/index');
        }
        else
        {      
            $data['course']=$this->Course_model->get_all_tblcourse(); 
            $data['teacher']=$this->Teacher_model->get_all_tblteacher();      
            $data['_view'] = 'courseteacher/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tblcourseteacher
     */
    function edit($id)
    {   
        // check if the tblcourseteacher exists before trying to edit it
        $data['tblcourseteacher'] = $this->Courseteacher_model->get_tblcourseteacher($id);
        
        if(isset($data['tblcourseteacher']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('course_id','Course Id','required|integer');
			$this->form_validation->set_rules('teacher_id','Teacher Id','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'course_id' => $this->input->post('course_id'),
					'teacher_id' => $this->input->post('teacher_id'),
                );

                $this->Courseteacher_model->update_tblcourseteacher($id,$params);            
                redirect('courseteacher/index');
            }
            else
            {
                $data['_view'] = 'courseteacher/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tblcourseteacher you are trying to edit does not exist.');
    } 

    /*
     * Deleting tblcourseteacher
     */
    function remove($id)
    {
        $tblcourseteacher = $this->Courseteacher_model->get_tblcourseteacher($id);

        // check if the tblcourseteacher exists before trying to delete it
        if(isset($tblcourseteacher['id']))
        {
            $this->Courseteacher_model->delete_tblcourseteacher($id);
            redirect('courseteacher/index');
        }
        else
            show_error('The tblcourseteacher you are trying to delete does not exist.');
    }
    
}
