<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Levelstudent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Levelstudent_model');
         $this->load->model('Level_model');
          $this->load->model('Student_model');
    } 

    /*
     * Listing of tbllevelstudent
     */
    function index()
    {
        $data['tbllevelstudent'] = $this->Levelstudent_model->get_all_tbllevelstudent_tblstudent_tbllevel();
        
        $data['_view'] = 'levelstudent/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbllevelstudent
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('level_id','Level Id','required');
		$this->form_validation->set_rules('student_id','Student Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'level_id' => $this->input->post('level_id'),
				'student_id' => $this->input->post('student_id'),
            );
            
            $tbllevelstudent_id = $this->Levelstudent_model->add_tbllevelstudent($params);
            redirect('levelstudent/index');
        }
        else
        {   
            $data['level']=$this->Level_model->get_all_tbllevel(); 
            $data['student']=$this->Student_model->get_all_tblstudent();         
            $data['_view'] = 'levelstudent/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbllevelstudent
     */
    function edit($id)
    {   
        // check if the tbllevelstudent exists before trying to edit it
        $data['tbllevelstudent'] = $this->Levelstudent_model->get_tbllevelstudent($id);
        
        if(isset($data['tbllevelstudent']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('level_id','Level Id','required|integer');
			$this->form_validation->set_rules('student_id','Student Id','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'level_id' => $this->input->post('level_id'),
					'student_id' => $this->input->post('student_id'),
                );

                $this->Levelstudent_model->update_tbllevelstudent($id,$params);            
                redirect('levelstudent/index');
            }
            else
            {
                $data['level']=$this->Level_model->get_all_tbllevel(); 
                $data['student']=$this->Student_model->get_all_tblstudent(); 
                $data['_view'] = 'levelstudent/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbllevelstudent you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbllevelstudent
     */
    function remove($id)
    {
        $tbllevelstudent = $this->Levelstudent_model->get_tbllevelstudent($id);

        // check if the tbllevelstudent exists before trying to delete it
        if(isset($tbllevelstudent['id']))
        {
            $this->Levelstudent_model->delete_tbllevelstudent($id);
            redirect('levelstudent/index');
        }
        else
            show_error('The tbllevelstudent you are trying to delete does not exist.');
    }
    
}
