<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Level extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Level_model');
    } 

    /*
     * Listing of tbllevel
     */
    function index()
    {
        $data['tbllevel'] = $this->Level_model->get_all_tbllevel();
        
        $data['_view'] = 'level/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbllevel
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('level_name','Level Name','required|max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'level_name' => $this->input->post('level_name'),
            );
            
            $tbllevel_id = $this->Level_model->add_tbllevel($params);
            redirect('level/index');
        }
        else
        {            
            $data['_view'] = 'level/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbllevel
     */
    function edit($level_id)
    {   
        // check if the tbllevel exists before trying to edit it
        $data['tbllevel'] = $this->Level_model->get_tbllevel($level_id);
        
        if(isset($data['tbllevel']['level_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('level_name','Level Name','required|max_length[20]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'level_name' => $this->input->post('level_name'),
                );

                $this->Level_model->update_tbllevel($level_id,$params);            
                redirect('level/index');
            }
            else
            {
                $data['_view'] = 'level/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbllevel you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbllevel
     */
    function remove($level_id)
    {
        $tbllevel = $this->Level_model->get_tbllevel($level_id);

        // check if the tbllevel exists before trying to delete it
        if(isset($tbllevel['level_id']))
        {
            $this->Level_model->delete_tbllevel($level_id);
            redirect('level/index');
        }
        else
            show_error('The tbllevel you are trying to delete does not exist.');
    }
    
}
