<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Courseteacher_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tblcourseteacher by id
     */
    function get_tblcourseteacher($id)
    {
        return $this->db->get_where('tblcourseteacher',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tblcourseteacher
     */
    function get_all_tblcourseteacher()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tblcourseteacher')->result_array();
    }
     function get_all_tblcourseteacher_tblteacher_tblcourse()
    {
         return $this->db->query("
            select tct.id,tct.course_id,tct.teacher_id,tc.course_name,tt.full_name as 'teacher_name' FROM
            tblcourseteacher tct inner join tblteacher tt on tct.teacher_id=tt.teacher_id
                                inner join tblcourse tc on tct.course_id=tc.course_id
            ")->result_array();
    }    
    /*
     * function to add new tblcourseteacher
     */
    function add_tblcourseteacher($params)
    {
        $this->db->insert('tblcourseteacher',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tblcourseteacher
     */
    function update_tblcourseteacher($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tblcourseteacher',$params);
    }
    
    /*
     * function to delete tblcourseteacher
     */
    function delete_tblcourseteacher($id)
    {
        return $this->db->delete('tblcourseteacher',array('id'=>$id));
    }
}
