<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    public function isIdAvailable(){
   
    $shcekDataAvailableOrNot=$this->db->get('tblcourse');
    if($shcekDataAvailableOrNot->num_rows() > 0){

    $query = $this->db->query("SELECT course_id FROM tblcourse ORDER BY course_id DESC LIMIT 1");
    $result = $query->row()->course_id;
    $result ++;
    return $result++;
    }else{
        return 2102;
    }
}
    /*
     * Get tblcourse by course_id
     */
    function get_tblcourse($course_id)
    {
        // return $this->db->get_where('tblcourse',array('course_id'=>$course_id))->row_array();
         return $this->db->query("
           select * FROM
           tblcourse tc inner join tbllevel tl on tl.level_id=tc.level_id
            where tc.course_id=$course_id
            ")->row_array();
    }
    //     public function get_tblcourse_tbllevel($course_id){
    //       return $this->db->query("
    //         select * FROM
    //         tblcourse tc inner join tbllevel tl on tl.level_id=tc.level_id
    //         where tc.course_id=$course_id
    //         ")->result_array();
    // }  
    /*
     * Get all tblcourse
     */
    function get_all_tblcourse()
    {
        $this->db->order_by('course_id', 'desc');
       
 return $this->db->get('tblcourse')->result_array();
        // return $this->db->query("
        //     select * FROM
        //     tblcourse tc inner join tbllevel tl on tl.level_id=tc.level_id
        //     ")->result_array();
    }

    public function get_all_tblcourse_tbllevel(){
          return $this->db->query("
            select * FROM
            tblcourse tc inner join tbllevel tl on tl.level_id=tc.level_id
            ")->result_array();
    }
        
    /*
     * function to add new tblcourse
     */
    function add_tblcourse($params)
    {
        $this->db->insert('tblcourse',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tblcourse
     */
    function update_tblcourse($course_id,$params)
    {
        $this->db->where('course_id',$course_id);
        return $this->db->update('tblcourse',$params);
    }
    
    /*
     * function to delete tblcourse
     */
    function delete_tblcourse($course_id)
    {
        return $this->db->delete('tblcourse',array('course_id'=>$course_id));
    }
}
