<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
      public function isIdAvailable(){
   
    $shcekDataAvailableOrNot=$this->db->get('tblstudent');
    if($shcekDataAvailableOrNot->num_rows() > 0){

    $query = $this->db->query("SELECT student_id FROM tblstudent ORDER BY student_id DESC LIMIT 1");
    $result = $query->row()->student_id;
    $result ++;
    return $result++;
    }else{
        return 250212;
    }
}
  
    /*
     * Get tblstudent by student_id
     */
    function get_tblstudent($student_id)
    {
        return $this->db->get_where('tblstudent',array('student_id'=>$student_id))->row_array();
    }
        
    /*
     * Get all tblstudent
     */
    function get_all_tblstudent()
    {
        $this->db->order_by('student_id', 'desc');
        return $this->db->get('tblstudent')->result_array();
    }
        
    /*
     * function to add new tblstudent
     */
    function add_tblstudent($params)
    {
        $this->db->insert('tblstudent',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tblstudent
     */
    function update_tblstudent($student_id,$params)
    {
        $this->db->where('student_id',$student_id);
        return $this->db->update('tblstudent',$params);
    }
    
    /*
     * function to delete tblstudent
     */
    function delete_tblstudent($student_id)
    {
        return $this->db->delete('tblstudent',array('student_id'=>$student_id));
    }
}
